import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import { api, ApiError } from "../api";
import type { Job } from "../types";
import { Badge, Button, Card, EmptyState, ErrorBanner, Spinner } from "../components/ui";

/** GET /jobs annotates each row with `candidate_count` (evaluations
 * written against it) on top of the frozen `Job` shape -- see
 * routers/jobs.py's module docstring for why. */
interface JobWithCount extends Job {
  candidate_count?: number;
}

interface JobsResponseWithCounts {
  jobs: JobWithCount[];
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

export default function Jobs() {
  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: ["jobs"],
    queryFn: () => api.listJobs() as Promise<JobsResponseWithCounts>,
  });

  const apiError = error as ApiError | null;
  const jobs = data?.jobs ?? [];

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold">Jobs</h1>
          <p className="text-sm text-[hsl(var(--muted-foreground))]">
            Every job description generated by JD Studio, with its candidate pipeline.
          </p>
        </div>
        <Link to="/jobs/new">
          <Button>New job</Button>
        </Link>
      </div>

      {isLoading && (
        <div className="flex items-center gap-2 text-sm text-[hsl(var(--muted-foreground))]">
          <Spinner size="sm" /> Loading jobs…
        </div>
      )}

      {isError && (
        <ErrorBanner
          code={apiError?.code ?? "unknown_error"}
          message={apiError?.message ?? "Failed to load jobs."}
          onRetry={() => refetch()}
        />
      )}

      {!isLoading && !isError && jobs.length === 0 && (
        <EmptyState
          title="No jobs yet"
          description="Create your first job description to start screening candidates."
          action={
            <Link to="/jobs/new">
              <Button>Create a job</Button>
            </Link>
          }
        />
      )}

      {!isLoading && !isError && jobs.length > 0 && (
        <Card>
          <div className="divide-y divide-[hsl(var(--border))]">
            {jobs.map((job) => {
              const candidateCount = job.candidate_count ?? 0;
              return (
                <Link
                  key={job.id}
                  to={`/jobs/${job.id}`}
                  className="flex flex-col gap-2 p-4 transition-colors hover:bg-[hsl(var(--muted))] sm:flex-row sm:items-center sm:justify-between"
                >
                  <div className="flex flex-col gap-1">
                    <span className="font-medium">{job.title}</span>
                    <span className="text-xs text-[hsl(var(--muted-foreground))]">
                      {job.level ?? "Level not set"} · {job.location ?? "Location not set"}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 text-xs text-[hsl(var(--muted-foreground))]">
                    <Badge variant="info">
                      {candidateCount} candidate{candidateCount === 1 ? "" : "s"}
                    </Badge>
                    <span>{formatDate(job.created_at)}</span>
                  </div>
                </Link>
              );
            })}
          </div>
        </Card>
      )}
    </div>
  );
}
